(()=>{
'use strict';
const DATA=window.GERDS_REZEPTE;
if(!DATA)return;
const DB_NAME='gerds-rezepte';
const DB_VERSION=1;
const FAVORITES='favorites';
const SHOPPING='shopping';
let dbPromise=null;
let favorites=new Set();
let shopping=[];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim();
const fmt=n=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(n);
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(FAVORITES))db.createObjectStore(FAVORITES,{keyPath:'recipeId'});if(!db.objectStoreNames.contains(SHOPPING))db.createObjectStore(SHOPPING,{keyPath:'key'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function getAll(store){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(store,'readonly').objectStore(store).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function put(store,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function del(store,key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function clear(store){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function replaceAll(store,values){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite'),os=tx.objectStore(store);os.clear();values.forEach(value=>os.put(value));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
const UNIT_ALIASES={'st':'Stk.','st.':'Stk.','stk':'Stk.','stück':'Stk.','stueck':'Stk.','l':'L','liter':'L','zwg':'Zweig','bd':'Bund','bund':'Bund','spritz':'Spritzer','scheib.':'Scheibe','msp':'Msp.','msp.':'Msp.'};
function canonicalUnit(unit){const raw=String(unit||'').trim();return UNIT_ALIASES[raw.toLowerCase()]||raw}
const UNIT_MAP={
  g:{dimension:'mass',factor:1,unit:'g'},kg:{dimension:'mass',factor:1000,unit:'g'},
  ml:{dimension:'volume',factor:1,unit:'ml'},cl:{dimension:'volume',factor:10,unit:'ml'},L:{dimension:'volume',factor:1000,unit:'ml'},
  EL:{dimension:'tablespoon',factor:1,unit:'EL'},TL:{dimension:'teaspoon',factor:1,unit:'TL'},'Msp.':{dimension:'knifeTip',factor:1,unit:'Msp.'},Prise:{dimension:'pinch',factor:1,unit:'Prise'},Spritzer:{dimension:'splash',factor:1,unit:'Spritzer'},
  'Stk.':{dimension:'count',factor:1,unit:'Stück'},Blatt:{dimension:'leaf',factor:1,unit:'Blatt'},Zweig:{dimension:'sprig',factor:1,unit:'Zweig'},Bund:{dimension:'bunch',factor:1,unit:'Bund'},Scheibe:{dimension:'slice',factor:1,unit:'Scheibe'},'Dösch.':{dimension:'pack',factor:1,unit:'Döschen'},Ds:{dimension:'can',factor:1,unit:'Dose'},Beet:{dimension:'bed',factor:1,unit:'Beet'}
};
function canonicalArticle(article){const raw=String(article||'').trim(),a=norm(raw);const m=a.match(/^(?:eier|ei(?: er)?) (?:grosse|groesse|klasse|gr|kl) (s|m|l|xl)$/);return m?`Eier Größe ${m[1].toUpperCase()}`:raw}
function isSizedEggArticle(article){return /^eier grosse (s|m|l|xl)$/.test(norm(canonicalArticle(article)))}
function qtyRange(q,factor){if(!q)return null;if(q.kind==='number')return {min:q.value*factor,max:q.value*factor};if(q.kind==='range')return {min:q.min*factor,max:q.max*factor};return null}
function normalizedAmount(ingredient,factor){const range=qtyRange(ingredient.quantity,factor);const unit=canonicalUnit(ingredient.unit);if(!range)return {dimension:'text',unit:'',min:null,max:null,text:ingredient.quantity?.text||'nach Bedarf'};const m=UNIT_MAP[unit];if(!m)return {dimension:`unit:${unit}`,unit:unit||'',min:range.min,max:range.max};return {dimension:m.dimension,unit:m.unit,min:range.min*m.factor,max:range.max*m.factor,text:''}}
function shoppingKey(article,dimension){return `${norm(canonicalArticle(article))}::${dimension}`}
function mergeAmount(a,b){if(a.dimension!==b.dimension)return a;const out={...a};if(Number.isFinite(a.min)&&Number.isFinite(b.min)){out.min=a.min+b.min;out.max=a.max+b.max}else if(!a.text)out.text=b.text;else if(b.text&&!a.text.includes(b.text))out.text=`${a.text}; ${b.text}`;return out}
async function migrateShopping(items){let changed=false;const merged=new Map();for(const original of items){let item={...original};const article=canonicalArticle(item.article);let dimension=item.dimension,unit=item.unit,min=item.min,max=item.max;if(isSizedEggArticle(article)&&dimension==='mass'&&unit==='g'&&Number.isFinite(min)&&Number.isFinite(max)){const cMin=min/50,cMax=max/50;if(Math.abs(cMin-Math.round(cMin))<.0001&&Math.abs(cMax-Math.round(cMax))<.0001){dimension='count';unit='Stück';min=cMin;max=cMax}}const key=shoppingKey(article,dimension);if(article!==item.article||key!==item.key||dimension!==item.dimension||unit!==item.unit||min!==item.min||max!==item.max)changed=true;item={...item,article,key,dimension,unit,min,max};const existing=merged.get(key);if(existing){changed=true;merged.set(key,{...existing,...mergeAmount(existing,item),done:existing.done&&item.done,sources:[...new Set([...(existing.sources||[]),...(item.sources||[])])],updatedAt:Math.max(existing.updatedAt||0,item.updatedAt||0)})}else merged.set(key,item)}const out=[...merged.values()];if(changed)await replaceAll(SHOPPING,out);return out}
function displayAmount(item){if(Number.isFinite(item.min)){let min=item.min,max=item.max,unit=item.unit;if(item.dimension==='mass'&&min>=1000&&max>=1000){min/=1000;max/=1000;unit='kg'}else if(item.dimension==='volume'&&min>=1000&&max>=1000){min/=1000;max/=1000;unit='L'}const q=Math.abs(max-min)<.0001?fmt(min):`${fmt(min)}–${fmt(max)}`;return `${q}${unit?` ${unit}`:''}`}return item.text||'nach Bedarf'}
function recipeById(id){return DATA.recipes.find(r=>r.id===id)}
function syncCardFavoriteButton(button,id){const saved=favorites.has(id),label=saved?'Aus Favoriten entfernen':'Zu Favoriten hinzufügen';button.classList.toggle('is-saved',saved);button.textContent=saved?'★':'☆';button.setAttribute('aria-label',label);button.setAttribute('aria-pressed',String(saved));button.title=label}
function syncDetailFavoriteButton(button,id){const saved=favorites.has(id),label=saved?'Aus Favoriten entfernen':'Als Favorit speichern';button.classList.toggle('is-saved',saved);button.textContent=saved?'★ Gespeichert':'☆ Als Favorit speichern';button.setAttribute('aria-label',label);button.setAttribute('aria-pressed',String(saved));button.title=label}
function syncFavoriteControls(id){document.querySelectorAll('[data-favorite]').forEach(button=>{if(button.dataset.favorite===id)syncCardFavoriteButton(button,id)});document.querySelectorAll('[data-detail-favorite]').forEach(button=>{if(button.dataset.detailFavorite===id)syncDetailFavoriteButton(button,id)})}
async function toggleFavorite(id){const wasSaved=favorites.has(id);if(wasSaved)favorites.delete(id);else favorites.add(id);updateCounts();syncFavoriteControls(id);try{if(wasSaved)await del(FAVORITES,id);else await put(FAVORITES,{recipeId:id,createdAt:Date.now()})}catch(error){if(wasSaved)favorites.add(id);else favorites.delete(id);updateCounts();syncFavoriteControls(id);console.warn('Favorit konnte nicht gespeichert werden.',error);return}if(currentListRoute()==='favorites')renderFavorites()}
function currentRecipe(){const m=(location.hash||'').match(/^#rezept=(.+)$/);return m?recipeById(decodeURIComponent(m[1])):null}
function currentTarget(r){const input=document.getElementById('portionInput');const v=Number(input?.value);return Number.isFinite(v)?v:(r.scaleType==='factor'?1:r.baseScale)}
function tableFactor(table,target,main){if(main.scaleType==='factor')return target;if(main.scaleType==='portions'&&table.scaleType==='portions')return target/table.baseScale;return target/main.baseScale}
async function addShoppingIngredient(recipe,table,ingredient,target){const factor=tableFactor(table,target,recipe);const article=canonicalArticle(ingredient.article);const amount=normalizedAmount(ingredient,factor);let key=shoppingKey(article,amount.dimension);let existing=shopping.find(x=>x.key===key);if(existing){existing={...existing,...mergeAmount(existing,amount),article,updatedAt:Date.now(),sources:[...new Set([...(existing.sources||[]),recipe.id])]};shopping=shopping.map(x=>x.key===key?existing:x)}else{existing={key,article,dimension:amount.dimension,unit:amount.unit,min:amount.min,max:amount.max,text:amount.text,done:false,sources:[recipe.id],createdAt:Date.now(),updatedAt:Date.now()};shopping.push(existing)}await put(SHOPPING,existing);updateCounts();decorate();}
async function removeShopping(key){shopping=shopping.filter(x=>x.key!==key);await del(SHOPPING,key);updateCounts();if(currentListRoute()==='shopping')renderShopping()}
async function toggleDone(key){const item=shopping.find(x=>x.key===key);if(!item)return;item.done=!item.done;await put(SHOPPING,item);renderShopping()}
function navHtml(){return ''}
function ensureNav(){const nav=document.querySelector('.topbar .nav');if(!nav)return;if(!nav.querySelector('[data-list-route="favorites"]'))nav.insertAdjacentHTML('beforeend','<button type="button" class="nav-list-button" data-list-route="favorites">Favoriten <span class="nav-count" data-fav-count></span></button><button type="button" class="nav-list-button" data-list-route="shopping">Einkaufsliste <span class="nav-count" data-shop-count></span></button>');nav.querySelectorAll('[data-list-route]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',()=>showList(btn.dataset.listRoute))});updateCounts()}
function updateCounts(){document.querySelectorAll('[data-fav-count]').forEach(x=>{x.textContent=favorites.size;x.hidden=!favorites.size});document.querySelectorAll('[data-shop-count]').forEach(x=>{x.textContent=shopping.length;x.hidden=!shopping.length})}
function currentListRoute(){return history.state?.route==='favorites'||location.hash==='#favoriten'?'favorites':history.state?.route==='shopping'||location.hash==='#einkaufsliste'?'shopping':''}
function showList(route,{write=true}={}){if(write)history.pushState({route},'',route==='favorites'?'#favoriten':'#einkaufsliste');document.body.dataset.route=route;document.body.classList.remove('has-hero');document.querySelector('.topbar')?.classList.add('is-stuck','show-brand');document.querySelectorAll('[data-route]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('[data-list-route]').forEach(x=>x.classList.toggle('active',x.dataset.listRoute===route));route==='favorites'?renderFavorites():renderShopping();scrollTo({top:0,behavior:'smooth'})}
function favoriteCard(r){const visual=r.images?.length?`<div class="card-visual has-image" style="--card-image:url('${encodeURI(r.images[0])}');--card-size-y:130%;--card-pos-y:54%;"></div>`:`<div class="card-visual no-image"><span class="card-initials">${esc(r.title.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span></div>`;return `<article class="recipe-card"><button class="list-card-button" type="button" data-open-favorite="${esc(r.id)}">${visual}<div class="card-body"><div class="card-taxonomy"><span class="category">${esc(r.category)}</span><span class="cuisine-badge">${esc(r.cuisine)}</span></div><h3>${esc(r.title)}</h3><div class="meta-row"><span>◷ ca. ${r.durationMinutes} Min.</span><span>·</span><span>${esc(r.scaleType==='portions'?`${fmt(r.baseScale)} Portionen`:r.scaleType==='batch'?`${fmt(r.baseScale)} kg Ansatz`:'1 × Rezept')}</span></div></div></button><button type="button" class="bookmark-btn is-saved" data-favorite="${esc(r.id)}" aria-label="Aus Favoriten entfernen" aria-pressed="true" title="Aus Favoriten entfernen">★</button></article>`}
function renderFavorites(){const app=document.getElementById('app');const rows=DATA.recipes.filter(r=>favorites.has(r.id)).sort((a,b)=>a.title.localeCompare(b.title,'de'));app.innerHTML=`<div class="list-page"><div class="shell"><div class="list-head"><div><span class="category">Gespeichert auf diesem Gerät</span><h1>Favoriten</h1><p>${rows.length?`${rows.length} gespeicherte${rows.length===1?'s Rezept':' Rezepte'}`:'Noch keine Rezepte gespeichert.'}</p></div>${rows.length?'<div class="list-actions"><button type="button" id="clearFavorites">Alle entfernen</button></div>':''}</div>${rows.length?`<div class="favorite-grid">${rows.map(favoriteCard).join('')}</div>`:'<div class="favorite-empty">Mit dem Lesezeichen-Symbol auf einer Rezeptkarte oder in der Detailansicht kannst du Rezepte hier ablegen.</div>'}</div></div>`;app.querySelectorAll('[data-open-favorite]').forEach(b=>b.addEventListener('click',()=>{history.pushState({route:'detail',id:b.dataset.openFavorite,fromArchive:false},'',`#rezept=${encodeURIComponent(b.dataset.openFavorite)}`);location.reload()}));app.querySelectorAll('[data-favorite]').forEach(b=>{syncCardFavoriteButton(b,b.dataset.favorite);b.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(b.dataset.favorite)})});document.getElementById('clearFavorites')?.addEventListener('click',async()=>{favorites.clear();await clear(FAVORITES);updateCounts();renderFavorites()})}
function renderShopping(){const app=document.getElementById('app');const rows=[...shopping].sort((a,b)=>Number(a.done)-Number(b.done)||a.article.localeCompare(b.article,'de'));app.innerHTML=`<div class="list-page"><div class="shell"><div class="list-head"><div><span class="category">Gespeichert auf diesem Gerät</span><h1>Einkaufsliste</h1><p>${rows.length?`${rows.length} Zutatenposition${rows.length===1?'':'en'}`:'Noch keine Zutaten hinzugefügt.'}</p></div>${rows.length?'<div class="list-actions"><button type="button" id="clearShopping">Liste leeren</button></div>':''}</div><p class="shopping-note">Gleiche Zutaten und direkt vergleichbare Einheiten werden zusammengefasst. Stück, Bund, Zweig, Blatt und Küchenmaße bleiben in ihrer ursprünglichen Einheit; es werden keine Schätzgewichte erzeugt.</p>${rows.length?`<div class="shopping-list">${rows.map(x=>`<div class="shopping-row ${x.done?'is-done':''}"><input class="shopping-check" type="checkbox" ${x.done?'checked':''} data-shop-done="${esc(x.key)}" aria-label="Erledigt"><div class="shopping-name"><strong>${esc(x.article)}</strong><small>${(x.sources||[]).length} Rezept${(x.sources||[]).length===1?'':'e'}</small></div><div class="shopping-amount">${esc(displayAmount(x))}</div><button class="shopping-remove" type="button" data-shop-remove="${esc(x.key)}" aria-label="Entfernen">×</button></div>`).join('')}</div>`:'<div class="shopping-empty">In einer Rezeptansicht einfach eine Zutat anklicken. Die aktuell eingestellte Portionsmenge wird dabei übernommen.</div>'}</div></div>`;app.querySelectorAll('[data-shop-done]').forEach(x=>x.addEventListener('change',()=>toggleDone(x.dataset.shopDone)));app.querySelectorAll('[data-shop-remove]').forEach(x=>x.addEventListener('click',()=>removeShopping(x.dataset.shopRemove)));document.getElementById('clearShopping')?.addEventListener('click',async()=>{shopping=[];await clear(SHOPPING);updateCounts();renderShopping()})}
function decorateCards(){document.querySelectorAll('.recipe-card').forEach(card=>{const open=card.querySelector('[data-recipe],[data-open-favorite]');if(!open)return;const id=open.dataset.recipe||open.dataset.openFavorite;let button=card.querySelector('.bookmark-btn');if(!button){card.insertAdjacentHTML('beforeend',`<button type="button" class="bookmark-btn" data-favorite="${esc(id)}"></button>`);button=card.querySelector('.bookmark-btn')}syncCardFavoriteButton(button,id);if(button.dataset.favoriteBound)return;button.dataset.favoriteBound='1';button.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(id)})})}
function decorateDetail(){const r=currentRecipe();if(!r)return;const hero=document.querySelector('.detail-hero > div');if(hero){let button=hero.querySelector('.detail-favorite');if(!button){hero.querySelector('.detail-meta')?.insertAdjacentHTML('afterend',`<button type="button" class="detail-favorite" data-detail-favorite="${esc(r.id)}"></button>`);button=hero.querySelector('.detail-favorite')}if(button){syncDetailFavoriteButton(button,r.id);if(!button.dataset.favoriteBound){button.dataset.favoriteBound='1';button.addEventListener('click',()=>toggleFavorite(r.id))}}}decorateIngredients(r)}
function decorateIngredients(r){const target=currentTarget(r);const attach=(root,table)=>{if(!root)return;const els=[...root.querySelectorAll('li.ingredient')];els.forEach((el,i)=>{const ing=table.ingredients[i];if(!ing||el.dataset.shoppingBound)return;el.dataset.shoppingBound='1';el.classList.add('is-shopping-enabled');el.title='Zur Einkaufsliste hinzufügen';const factor=tableFactor(table,target,r);const amt=normalizedAmount(ing,factor);const key=shoppingKey(canonicalArticle(ing.article),amt.dimension);el.classList.toggle('is-in-shopping',shopping.some(x=>x.key===key));el.addEventListener('click',e=>{if(e.target.closest('.glossary-term'))return;addShoppingIngredient(r,table,ing,currentTarget(r))})})};attach(document.getElementById('mainIngredients'),r);const subRoot=document.getElementById('subrecipes');if(subRoot)[...subRoot.querySelectorAll('.subrecipe')].forEach((details,i)=>attach(details,r.subrecipes[i]))}
function decorate(){ensureNav();decorateCards();decorateDetail();const route=currentListRoute();document.querySelectorAll('[data-list-route]').forEach(x=>x.classList.toggle('active',x.dataset.listRoute===route))}
const observer=new MutationObserver(()=>requestAnimationFrame(decorate));observer.observe(document.body,{childList:true,subtree:true});
window.addEventListener('popstate',()=>setTimeout(()=>{const route=currentListRoute();if(route)showList(route,{write:false});else decorate()},0));
(async()=>{try{favorites=new Set((await getAll(FAVORITES)).map(x=>x.recipeId));shopping=await migrateShopping(await getAll(SHOPPING))}catch(e){console.warn('Listen konnten nicht aus IndexedDB geladen werden.',e)}ensureNav();updateCounts();const route=currentListRoute();if(route)showList(route,{write:false});else decorate()})();
})();